### ISSUE TITLE
PSA example build failed

### ISSUE THREAD

**Issue by rajkan01** [ARMmbed/mbed-os-example-psa#5]
Followed the procedure and build command  `mbed compile -m CY8CKIT_064S2_4343W -t GCC_ARM` suggested by this example readme but CY8CKIT_064S2_4343W target is not recognized by Mbed-CLI with error ```argument -m/--mcu: CY8CKIT_064S2_4343W is not a supported MCU.```

**Comment by LDong-Arm** [comment]
@rajkan01 
The documentation is outdated. Now we have CY8CKIT064B0S2_4343W (which doesn't support PSA) and CYTFM_064B0S2_4343W (which supports PSA), I guess the latter is the replacement.
Anyway, it's okay to compile for any PSA-supported targets, such as MUSCA_S1.

@jainvikas8

**Comment by jainvikas8** [comment]
@LDong-Arm We should raise a PR to update the documentation (README.md) in this repo. Replace with a working example, so that user can directly copy & paste the code snippet to build.

**Comment by LDong-Arm** [comment]
PR created: https://github.com/ARMmbed/mbed-os-example-psa/pull/13
